### ISSUE TITLE
deletion of javaml-0.1.1.jar and openCASA_.jar

### ISSUE THREAD

**Issue by cfneez** [calquezar/OpenCASA#3]
Hello, 
I see javaml-0.1.1.jar and openCASA_.jar were deleted on Jan 9, 2020. Can you please tell me why and if these will be replaced with newer plug-in (jar) files? We have been using openCASA over the summer and I needed to download the plug-in on a new machine and found they had been deleted. We will be continuing to need these plug ins for the foreseeable future.   

Thanks!

**Comment by calquezar** [comment]
Hi cfneez!
I deleted the file OpenCASA_.jar related to the version 2.0, because it is under development at this time, and I thought that people could use it thinking that it is a final version. If you are using the new features, just be conscious that it is a beta version. Otherwise, if you are using the modules released in the previous version, I recommend to you the OpenCASA v1.0 that you will find here: https://github.com/calquezar/OpenCASA/tree/master/executables/v1.0

In case you need to use the same plugin in other computer, you could just copy the same .jar that you have in one computer, to the other.
If you have any question or doubt, please do not hesitate to contact me :)
Best,
Carlos

**Comment by calquezar** [comment]
Sorry, to be more explicit about your question "Can you please tell me why and if these will be replaced with newer plug-in (jar) files?" the answer is: yes, we are working in the new version, and we hope to release it this spring.
